board: first_8_pins_sweep
stop_on_fail: false
pins_type: iiiiiiiizzzzzzzzoooooooozzzzzzzz
tests:
- name: input=00000000
  input: '00000000'
  expected: xxxxxxxx
- name: input=00000001
  input: '00000001'
  expected: xxxxxxxx
- name: input=00000010
  input: '00000010'
  expected: xxxxxxxx
- name: input=00000011
  input: '00000011'
  expected: xxxxxxxx
- name: input=00000100
  input: '00000100'
  expected: xxxxxxxx
- name: input=00000101
  input: '00000101'
  expected: xxxxxxxx
- name: input=00000110
  input: '00000110'
  expected: xxxxxxxx
- name: input=00000111
  input: '00000111'
  expected: xxxxxxxx
- name: input=00001000
  input: '00001000'
  expected: xxxxxxxx
- name: input=00001001
  input: '00001001'
  expected: xxxxxxxx
- name: input=00001010
  input: '00001010'
  expected: xxxxxxxx
- name: input=00001011
  input: '00001011'
  expected: xxxxxxxx
- name: input=00001100
  input: '00001100'
  expected: xxxxxxxx
- name: input=00001101
  input: '00001101'
  expected: xxxxxxxx
- name: input=00001110
  input: '00001110'
  expected: xxxxxxxx
- name: input=00001111
  input: '00001111'
  expected: xxxxxxxx
- name: input=00010000
  input: '00010000'
  expected: xxxxxxxx
- name: input=00010001
  input: '00010001'
  expected: xxxxxxxx
- name: input=00010010
  input: '00010010'
  expected: xxxxxxxx
- name: input=00010011
  input: '00010011'
  expected: xxxxxxxx
- name: input=00010100
  input: '00010100'
  expected: xxxxxxxx
- name: input=00010101
  input: '00010101'
  expected: xxxxxxxx
- name: input=00010110
  input: '00010110'
  expected: xxxxxxxx
- name: input=00010111
  input: '00010111'
  expected: xxxxxxxx
- name: input=00011000
  input: '00011000'
  expected: xxxxxxxx
- name: input=00011001
  input: '00011001'
  expected: xxxxxxxx
- name: input=00011010
  input: '00011010'
  expected: xxxxxxxx
- name: input=00011011
  input: '00011011'
  expected: xxxxxxxx
- name: input=00011100
  input: '00011100'
  expected: xxxxxxxx
- name: input=00011101
  input: '00011101'
  expected: xxxxxxxx
- name: input=00011110
  input: '00011110'
  expected: xxxxxxxx
- name: input=00011111
  input: '00011111'
  expected: xxxxxxxx
- name: input=00100000
  input: '00100000'
  expected: xxxxxxxx
- name: input=00100001
  input: '00100001'
  expected: xxxxxxxx
- name: input=00100010
  input: '00100010'
  expected: xxxxxxxx
- name: input=00100011
  input: '00100011'
  expected: xxxxxxxx
- name: input=00100100
  input: '00100100'
  expected: xxxxxxxx
- name: input=00100101
  input: '00100101'
  expected: xxxxxxxx
- name: input=00100110
  input: '00100110'
  expected: xxxxxxxx
- name: input=00100111
  input: '00100111'
  expected: xxxxxxxx
- name: input=00101000
  input: '00101000'
  expected: xxxxxxxx
- name: input=00101001
  input: '00101001'
  expected: xxxxxxxx
- name: input=00101010
  input: '00101010'
  expected: xxxxxxxx
- name: input=00101011
  input: '00101011'
  expected: xxxxxxxx
- name: input=00101100
  input: '00101100'
  expected: xxxxxxxx
- name: input=00101101
  input: '00101101'
  expected: xxxxxxxx
- name: input=00101110
  input: '00101110'
  expected: xxxxxxxx
- name: input=00101111
  input: '00101111'
  expected: xxxxxxxx
- name: input=00110000
  input: '00110000'
  expected: xxxxxxxx
- name: input=00110001
  input: '00110001'
  expected: xxxxxxxx
- name: input=00110010
  input: '00110010'
  expected: xxxxxxxx
- name: input=00110011
  input: '00110011'
  expected: xxxxxxxx
- name: input=00110100
  input: '00110100'
  expected: xxxxxxxx
- name: input=00110101
  input: '00110101'
  expected: xxxxxxxx
- name: input=00110110
  input: '00110110'
  expected: xxxxxxxx
- name: input=00110111
  input: '00110111'
  expected: xxxxxxxx
- name: input=00111000
  input: '00111000'
  expected: xxxxxxxx
- name: input=00111001
  input: '00111001'
  expected: xxxxxxxx
- name: input=00111010
  input: '00111010'
  expected: xxxxxxxx
- name: input=00111011
  input: '00111011'
  expected: xxxxxxxx
- name: input=00111100
  input: '00111100'
  expected: xxxxxxxx
- name: input=00111101
  input: '00111101'
  expected: xxxxxxxx
- name: input=00111110
  input: '00111110'
  expected: xxxxxxxx
- name: input=00111111
  input: '00111111'
  expected: xxxxxxxx
- name: input=01000000
  input: '01000000'
  expected: xxxxxxxx
- name: input=01000001
  input: '01000001'
  expected: xxxxxxxx
- name: input=01000010
  input: '01000010'
  expected: xxxxxxxx
- name: input=01000011
  input: '01000011'
  expected: xxxxxxxx
- name: input=01000100
  input: '01000100'
  expected: xxxxxxxx
- name: input=01000101
  input: '01000101'
  expected: xxxxxxxx
- name: input=01000110
  input: '01000110'
  expected: xxxxxxxx
- name: input=01000111
  input: '01000111'
  expected: xxxxxxxx
- name: input=01001000
  input: '01001000'
  expected: xxxxxxxx
- name: input=01001001
  input: '01001001'
  expected: xxxxxxxx
- name: input=01001010
  input: '01001010'
  expected: xxxxxxxx
- name: input=01001011
  input: '01001011'
  expected: xxxxxxxx
- name: input=01001100
  input: '01001100'
  expected: xxxxxxxx
- name: input=01001101
  input: '01001101'
  expected: xxxxxxxx
- name: input=01001110
  input: '01001110'
  expected: xxxxxxxx
- name: input=01001111
  input: '01001111'
  expected: xxxxxxxx
- name: input=01010000
  input: '01010000'
  expected: xxxxxxxx
- name: input=01010001
  input: '01010001'
  expected: xxxxxxxx
- name: input=01010010
  input: '01010010'
  expected: xxxxxxxx
- name: input=01010011
  input: '01010011'
  expected: xxxxxxxx
- name: input=01010100
  input: '01010100'
  expected: xxxxxxxx
- name: input=01010101
  input: '01010101'
  expected: xxxxxxxx
- name: input=01010110
  input: '01010110'
  expected: xxxxxxxx
- name: input=01010111
  input: '01010111'
  expected: xxxxxxxx
- name: input=01011000
  input: '01011000'
  expected: xxxxxxxx
- name: input=01011001
  input: '01011001'
  expected: xxxxxxxx
- name: input=01011010
  input: '01011010'
  expected: xxxxxxxx
- name: input=01011011
  input: '01011011'
  expected: xxxxxxxx
- name: input=01011100
  input: '01011100'
  expected: xxxxxxxx
- name: input=01011101
  input: '01011101'
  expected: xxxxxxxx
- name: input=01011110
  input: '01011110'
  expected: xxxxxxxx
- name: input=01011111
  input: '01011111'
  expected: xxxxxxxx
- name: input=01100000
  input: '01100000'
  expected: xxxxxxxx
- name: input=01100001
  input: '01100001'
  expected: xxxxxxxx
- name: input=01100010
  input: '01100010'
  expected: xxxxxxxx
- name: input=01100011
  input: '01100011'
  expected: xxxxxxxx
- name: input=01100100
  input: '01100100'
  expected: xxxxxxxx
- name: input=01100101
  input: '01100101'
  expected: xxxxxxxx
- name: input=01100110
  input: '01100110'
  expected: xxxxxxxx
- name: input=01100111
  input: '01100111'
  expected: xxxxxxxx
- name: input=01101000
  input: '01101000'
  expected: xxxxxxxx
- name: input=01101001
  input: '01101001'
  expected: xxxxxxxx
- name: input=01101010
  input: '01101010'
  expected: xxxxxxxx
- name: input=01101011
  input: '01101011'
  expected: xxxxxxxx
- name: input=01101100
  input: '01101100'
  expected: xxxxxxxx
- name: input=01101101
  input: '01101101'
  expected: xxxxxxxx
- name: input=01101110
  input: '01101110'
  expected: xxxxxxxx
- name: input=01101111
  input: '01101111'
  expected: xxxxxxxx
- name: input=01110000
  input: '01110000'
  expected: xxxxxxxx
- name: input=01110001
  input: '01110001'
  expected: xxxxxxxx
- name: input=01110010
  input: '01110010'
  expected: xxxxxxxx
- name: input=01110011
  input: '01110011'
  expected: xxxxxxxx
- name: input=01110100
  input: '01110100'
  expected: xxxxxxxx
- name: input=01110101
  input: '01110101'
  expected: xxxxxxxx
- name: input=01110110
  input: '01110110'
  expected: xxxxxxxx
- name: input=01110111
  input: '01110111'
  expected: xxxxxxxx
- name: input=01111000
  input: '01111000'
  expected: xxxxxxxx
- name: input=01111001
  input: '01111001'
  expected: xxxxxxxx
- name: input=01111010
  input: '01111010'
  expected: xxxxxxxx
- name: input=01111011
  input: '01111011'
  expected: xxxxxxxx
- name: input=01111100
  input: '01111100'
  expected: xxxxxxxx
- name: input=01111101
  input: '01111101'
  expected: xxxxxxxx
- name: input=01111110
  input: '01111110'
  expected: xxxxxxxx
- name: input=01111111
  input: '01111111'
  expected: xxxxxxxx
- name: input=10000000
  input: '10000000'
  expected: xxxxxxxx
- name: input=10000001
  input: '10000001'
  expected: xxxxxxxx
- name: input=10000010
  input: '10000010'
  expected: xxxxxxxx
- name: input=10000011
  input: '10000011'
  expected: xxxxxxxx
- name: input=10000100
  input: '10000100'
  expected: xxxxxxxx
- name: input=10000101
  input: '10000101'
  expected: xxxxxxxx
- name: input=10000110
  input: '10000110'
  expected: xxxxxxxx
- name: input=10000111
  input: '10000111'
  expected: xxxxxxxx
- name: input=10001000
  input: '10001000'
  expected: xxxxxxxx
- name: input=10001001
  input: '10001001'
  expected: xxxxxxxx
- name: input=10001010
  input: '10001010'
  expected: xxxxxxxx
- name: input=10001011
  input: '10001011'
  expected: xxxxxxxx
- name: input=10001100
  input: '10001100'
  expected: xxxxxxxx
- name: input=10001101
  input: '10001101'
  expected: xxxxxxxx
- name: input=10001110
  input: '10001110'
  expected: xxxxxxxx
- name: input=10001111
  input: '10001111'
  expected: xxxxxxxx
- name: input=10010000
  input: '10010000'
  expected: xxxxxxxx
- name: input=10010001
  input: '10010001'
  expected: xxxxxxxx
- name: input=10010010
  input: '10010010'
  expected: xxxxxxxx
- name: input=10010011
  input: '10010011'
  expected: xxxxxxxx
- name: input=10010100
  input: '10010100'
  expected: xxxxxxxx
- name: input=10010101
  input: '10010101'
  expected: xxxxxxxx
- name: input=10010110
  input: '10010110'
  expected: xxxxxxxx
- name: input=10010111
  input: '10010111'
  expected: xxxxxxxx
- name: input=10011000
  input: '10011000'
  expected: xxxxxxxx
- name: input=10011001
  input: '10011001'
  expected: xxxxxxxx
- name: input=10011010
  input: '10011010'
  expected: xxxxxxxx
- name: input=10011011
  input: '10011011'
  expected: xxxxxxxx
- name: input=10011100
  input: '10011100'
  expected: xxxxxxxx
- name: input=10011101
  input: '10011101'
  expected: xxxxxxxx
- name: input=10011110
  input: '10011110'
  expected: xxxxxxxx
- name: input=10011111
  input: '10011111'
  expected: xxxxxxxx
- name: input=10100000
  input: '10100000'
  expected: xxxxxxxx
- name: input=10100001
  input: '10100001'
  expected: xxxxxxxx
- name: input=10100010
  input: '10100010'
  expected: xxxxxxxx
- name: input=10100011
  input: '10100011'
  expected: xxxxxxxx
- name: input=10100100
  input: '10100100'
  expected: xxxxxxxx
- name: input=10100101
  input: '10100101'
  expected: xxxxxxxx
- name: input=10100110
  input: '10100110'
  expected: xxxxxxxx
- name: input=10100111
  input: '10100111'
  expected: xxxxxxxx
- name: input=10101000
  input: '10101000'
  expected: xxxxxxxx
- name: input=10101001
  input: '10101001'
  expected: xxxxxxxx
- name: input=10101010
  input: '10101010'
  expected: xxxxxxxx
- name: input=10101011
  input: '10101011'
  expected: xxxxxxxx
- name: input=10101100
  input: '10101100'
  expected: xxxxxxxx
- name: input=10101101
  input: '10101101'
  expected: xxxxxxxx
- name: input=10101110
  input: '10101110'
  expected: xxxxxxxx
- name: input=10101111
  input: '10101111'
  expected: xxxxxxxx
- name: input=10110000
  input: '10110000'
  expected: xxxxxxxx
- name: input=10110001
  input: '10110001'
  expected: xxxxxxxx
- name: input=10110010
  input: '10110010'
  expected: xxxxxxxx
- name: input=10110011
  input: '10110011'
  expected: xxxxxxxx
- name: input=10110100
  input: '10110100'
  expected: xxxxxxxx
- name: input=10110101
  input: '10110101'
  expected: xxxxxxxx
- name: input=10110110
  input: '10110110'
  expected: xxxxxxxx
- name: input=10110111
  input: '10110111'
  expected: xxxxxxxx
- name: input=10111000
  input: '10111000'
  expected: xxxxxxxx
- name: input=10111001
  input: '10111001'
  expected: xxxxxxxx
- name: input=10111010
  input: '10111010'
  expected: xxxxxxxx
- name: input=10111011
  input: '10111011'
  expected: xxxxxxxx
- name: input=10111100
  input: '10111100'
  expected: xxxxxxxx
- name: input=10111101
  input: '10111101'
  expected: xxxxxxxx
- name: input=10111110
  input: '10111110'
  expected: xxxxxxxx
- name: input=10111111
  input: '10111111'
  expected: xxxxxxxx
- name: input=11000000
  input: '11000000'
  expected: xxxxxxxx
- name: input=11000001
  input: '11000001'
  expected: xxxxxxxx
- name: input=11000010
  input: '11000010'
  expected: xxxxxxxx
- name: input=11000011
  input: '11000011'
  expected: xxxxxxxx
- name: input=11000100
  input: '11000100'
  expected: xxxxxxxx
- name: input=11000101
  input: '11000101'
  expected: xxxxxxxx
- name: input=11000110
  input: '11000110'
  expected: xxxxxxxx
- name: input=11000111
  input: '11000111'
  expected: xxxxxxxx
- name: input=11001000
  input: '11001000'
  expected: xxxxxxxx
- name: input=11001001
  input: '11001001'
  expected: xxxxxxxx
- name: input=11001010
  input: '11001010'
  expected: xxxxxxxx
- name: input=11001011
  input: '11001011'
  expected: xxxxxxxx
- name: input=11001100
  input: '11001100'
  expected: xxxxxxxx
- name: input=11001101
  input: '11001101'
  expected: xxxxxxxx
- name: input=11001110
  input: '11001110'
  expected: xxxxxxxx
- name: input=11001111
  input: '11001111'
  expected: xxxxxxxx
- name: input=11010000
  input: '11010000'
  expected: xxxxxxxx
- name: input=11010001
  input: '11010001'
  expected: xxxxxxxx
- name: input=11010010
  input: '11010010'
  expected: xxxxxxxx
- name: input=11010011
  input: '11010011'
  expected: xxxxxxxx
- name: input=11010100
  input: '11010100'
  expected: xxxxxxxx
- name: input=11010101
  input: '11010101'
  expected: xxxxxxxx
- name: input=11010110
  input: '11010110'
  expected: xxxxxxxx
- name: input=11010111
  input: '11010111'
  expected: xxxxxxxx
- name: input=11011000
  input: '11011000'
  expected: xxxxxxxx
- name: input=11011001
  input: '11011001'
  expected: xxxxxxxx
- name: input=11011010
  input: '11011010'
  expected: xxxxxxxx
- name: input=11011011
  input: '11011011'
  expected: xxxxxxxx
- name: input=11011100
  input: '11011100'
  expected: xxxxxxxx
- name: input=11011101
  input: '11011101'
  expected: xxxxxxxx
- name: input=11011110
  input: '11011110'
  expected: xxxxxxxx
- name: input=11011111
  input: '11011111'
  expected: xxxxxxxx
- name: input=11100000
  input: '11100000'
  expected: xxxxxxxx
- name: input=11100001
  input: '11100001'
  expected: xxxxxxxx
- name: input=11100010
  input: '11100010'
  expected: xxxxxxxx
- name: input=11100011
  input: '11100011'
  expected: xxxxxxxx
- name: input=11100100
  input: '11100100'
  expected: xxxxxxxx
- name: input=11100101
  input: '11100101'
  expected: xxxxxxxx
- name: input=11100110
  input: '11100110'
  expected: xxxxxxxx
- name: input=11100111
  input: '11100111'
  expected: xxxxxxxx
- name: input=11101000
  input: '11101000'
  expected: xxxxxxxx
- name: input=11101001
  input: '11101001'
  expected: xxxxxxxx
- name: input=11101010
  input: '11101010'
  expected: xxxxxxxx
- name: input=11101011
  input: '11101011'
  expected: xxxxxxxx
- name: input=11101100
  input: '11101100'
  expected: xxxxxxxx
- name: input=11101101
  input: '11101101'
  expected: xxxxxxxx
- name: input=11101110
  input: '11101110'
  expected: xxxxxxxx
- name: input=11101111
  input: '11101111'
  expected: xxxxxxxx
- name: input=11110000
  input: '11110000'
  expected: xxxxxxxx
- name: input=11110001
  input: '11110001'
  expected: xxxxxxxx
- name: input=11110010
  input: '11110010'
  expected: xxxxxxxx
- name: input=11110011
  input: '11110011'
  expected: xxxxxxxx
- name: input=11110100
  input: '11110100'
  expected: xxxxxxxx
- name: input=11110101
  input: '11110101'
  expected: xxxxxxxx
- name: input=11110110
  input: '11110110'
  expected: xxxxxxxx
- name: input=11110111
  input: '11110111'
  expected: xxxxxxxx
- name: input=11111000
  input: '11111000'
  expected: xxxxxxxx
- name: input=11111001
  input: '11111001'
  expected: xxxxxxxx
- name: input=11111010
  input: '11111010'
  expected: xxxxxxxx
- name: input=11111011
  input: '11111011'
  expected: xxxxxxxx
- name: input=11111100
  input: '11111100'
  expected: xxxxxxxx
- name: input=11111101
  input: '11111101'
  expected: xxxxxxxx
- name: input=11111110
  input: '11111110'
  expected: xxxxxxxx
- name: input=11111111
  input: '11111111'
  expected: xxxxxxxx
