chip: 74HC04 NOT
package: DIP14_left
stop_on_fail: true
tests:
- name: inputs=000000
  frame: 0z0z0zgzzz0z0z0v
  expect: x1x1x1xxx1x1x1xx
- name: inputs=000001
  frame: 1z0z0zgzzz0z0z0v
  expect: x0x1x1xxx1x1x1xx
- name: inputs=000010
  frame: 0z1z0zgzzz0z0z0v
  expect: x1x0x1xxx1x1x1xx
- name: inputs=000011
  frame: 1z1z0zgzzz0z0z0v
  expect: x0x0x1xxx1x1x1xx
- name: inputs=000100
  frame: 0z0z1zgzzz0z0z0v
  expect: x1x1x0xxx1x1x1xx
- name: inputs=000101
  frame: 1z0z1zgzzz0z0z0v
  expect: x0x1x0xxx1x1x1xx
- name: inputs=000110
  frame: 0z1z1zgzzz0z0z0v
  expect: x1x0x0xxx1x1x1xx
- name: inputs=000111
  frame: 1z1z1zgzzz0z0z0v
  expect: x0x0x0xxx1x1x1xx
- name: inputs=001000
  frame: 0z0z0zgzzz1z0z0v
  expect: x1x1x1xxx0x1x1xx
- name: inputs=001001
  frame: 1z0z0zgzzz1z0z0v
  expect: x0x1x1xxx0x1x1xx
- name: inputs=001010
  frame: 0z1z0zgzzz1z0z0v
  expect: x1x0x1xxx0x1x1xx
- name: inputs=001011
  frame: 1z1z0zgzzz1z0z0v
  expect: x0x0x1xxx0x1x1xx
- name: inputs=001100
  frame: 0z0z1zgzzz1z0z0v
  expect: x1x1x0xxx0x1x1xx
- name: inputs=001101
  frame: 1z0z1zgzzz1z0z0v
  expect: x0x1x0xxx0x1x1xx
- name: inputs=001110
  frame: 0z1z1zgzzz1z0z0v
  expect: x1x0x0xxx0x1x1xx
- name: inputs=001111
  frame: 1z1z1zgzzz1z0z0v
  expect: x0x0x0xxx0x1x1xx
- name: inputs=010000
  frame: 0z0z0zgzzz0z1z0v
  expect: x1x1x1xxx1x0x1xx
- name: inputs=010001
  frame: 1z0z0zgzzz0z1z0v
  expect: x0x1x1xxx1x0x1xx
- name: inputs=010010
  frame: 0z1z0zgzzz0z1z0v
  expect: x1x0x1xxx1x0x1xx
- name: inputs=010011
  frame: 1z1z0zgzzz0z1z0v
  expect: x0x0x1xxx1x0x1xx
- name: inputs=010100
  frame: 0z0z1zgzzz0z1z0v
  expect: x1x1x0xxx1x0x1xx
- name: inputs=010101
  frame: 1z0z1zgzzz0z1z0v
  expect: x0x1x0xxx1x0x1xx
- name: inputs=010110
  frame: 0z1z1zgzzz0z1z0v
  expect: x1x0x0xxx1x0x1xx
- name: inputs=010111
  frame: 1z1z1zgzzz0z1z0v
  expect: x0x0x0xxx1x0x1xx
- name: inputs=011000
  frame: 0z0z0zgzzz1z1z0v
  expect: x1x1x1xxx0x0x1xx
- name: inputs=011001
  frame: 1z0z0zgzzz1z1z0v
  expect: x0x1x1xxx0x0x1xx
- name: inputs=011010
  frame: 0z1z0zgzzz1z1z0v
  expect: x1x0x1xxx0x0x1xx
- name: inputs=011011
  frame: 1z1z0zgzzz1z1z0v
  expect: x0x0x1xxx0x0x1xx
- name: inputs=011100
  frame: 0z0z1zgzzz1z1z0v
  expect: x1x1x0xxx0x0x1xx
- name: inputs=011101
  frame: 1z0z1zgzzz1z1z0v
  expect: x0x1x0xxx0x0x1xx
- name: inputs=011110
  frame: 0z1z1zgzzz1z1z0v
  expect: x1x0x0xxx0x0x1xx
- name: inputs=011111
  frame: 1z1z1zgzzz1z1z0v
  expect: x0x0x0xxx0x0x1xx
- name: inputs=100000
  frame: 0z0z0zgzzz0z0z1v
  expect: x1x1x1xxx1x1x0xx
- name: inputs=100001
  frame: 1z0z0zgzzz0z0z1v
  expect: x0x1x1xxx1x1x0xx
- name: inputs=100010
  frame: 0z1z0zgzzz0z0z1v
  expect: x1x0x1xxx1x1x0xx
- name: inputs=100011
  frame: 1z1z0zgzzz0z0z1v
  expect: x0x0x1xxx1x1x0xx
- name: inputs=100100
  frame: 0z0z1zgzzz0z0z1v
  expect: x1x1x0xxx1x1x0xx
- name: inputs=100101
  frame: 1z0z1zgzzz0z0z1v
  expect: x0x1x0xxx1x1x0xx
- name: inputs=100110
  frame: 0z1z1zgzzz0z0z1v
  expect: x1x0x0xxx1x1x0xx
- name: inputs=100111
  frame: 1z1z1zgzzz0z0z1v
  expect: x0x0x0xxx1x1x0xx
- name: inputs=101000
  frame: 0z0z0zgzzz1z0z1v
  expect: x1x1x1xxx0x1x0xx
- name: inputs=101001
  frame: 1z0z0zgzzz1z0z1v
  expect: x0x1x1xxx0x1x0xx
- name: inputs=101010
  frame: 0z1z0zgzzz1z0z1v
  expect: x1x0x1xxx0x1x0xx
- name: inputs=101011
  frame: 1z1z0zgzzz1z0z1v
  expect: x0x0x1xxx0x1x0xx
- name: inputs=101100
  frame: 0z0z1zgzzz1z0z1v
  expect: x1x1x0xxx0x1x0xx
- name: inputs=101101
  frame: 1z0z1zgzzz1z0z1v
  expect: x0x1x0xxx0x1x0xx
- name: inputs=101110
  frame: 0z1z1zgzzz1z0z1v
  expect: x1x0x0xxx0x1x0xx
- name: inputs=101111
  frame: 1z1z1zgzzz1z0z1v
  expect: x0x0x0xxx0x1x0xx
- name: inputs=110000
  frame: 0z0z0zgzzz0z1z1v
  expect: x1x1x1xxx1x0x0xx
- name: inputs=110001
  frame: 1z0z0zgzzz0z1z1v
  expect: x0x1x1xxx1x0x0xx
- name: inputs=110010
  frame: 0z1z0zgzzz0z1z1v
  expect: x1x0x1xxx1x0x0xx
- name: inputs=110011
  frame: 1z1z0zgzzz0z1z1v
  expect: x0x0x1xxx1x0x0xx
- name: inputs=110100
  frame: 0z0z1zgzzz0z1z1v
  expect: x1x1x0xxx1x0x0xx
- name: inputs=110101
  frame: 1z0z1zgzzz0z1z1v
  expect: x0x1x0xxx1x0x0xx
- name: inputs=110110
  frame: 0z1z1zgzzz0z1z1v
  expect: x1x0x0xxx1x0x0xx
- name: inputs=110111
  frame: 1z1z1zgzzz0z1z1v
  expect: x0x0x0xxx1x0x0xx
- name: inputs=111000
  frame: 0z0z0zgzzz1z1z1v
  expect: x1x1x1xxx0x0x0xx
- name: inputs=111001
  frame: 1z0z0zgzzz1z1z1v
  expect: x0x1x1xxx0x0x0xx
- name: inputs=111010
  frame: 0z1z0zgzzz1z1z1v
  expect: x1x0x1xxx0x0x0xx
- name: inputs=111011
  frame: 1z1z0zgzzz1z1z1v
  expect: x0x0x1xxx0x0x0xx
- name: inputs=111100
  frame: 0z0z1zgzzz1z1z1v
  expect: x1x1x0xxx0x0x0xx
- name: inputs=111101
  frame: 1z0z1zgzzz1z1z1v
  expect: x0x1x0xxx0x0x0xx
- name: inputs=111110
  frame: 0z1z1zgzzz1z1z1v
  expect: x1x0x0xxx0x0x0xx
- name: inputs=111111
  frame: 1z1z1zgzzz1z1z1v
  expect: x0x0x0xxx0x0x0xx
